# Enter remote user
remote_user: root  # User ansible will use to issue commands

# Enter the location for the plugins package
heat_plugins_pkg_location: git+https://github.com/F5Networks/f5-openstack-heat-plugins.git@newton # Ex: git+https://github.com/F5Networks/f5-openstack-heat-plugins.git@mitaka

# Enter the location for the pip installed heat plugin packaged
pip_install_dest: /usr/lib/python2.7/site-packages/f5_heat  # Ex: /usr/lib/python2.7/site-packages/f5_heat

# Enter the location where the heat engine expects the heat plugins to be
# Do not use a trailing slash in this directory path!
heat_plugin_install_dest: : /usr/lib/heat  # Ex: /usr/lib/heat

# Enter the location where the heat enginer expects to find the f5_heat plugin
heat_plugin_f5_dst: /usr/lib/heat/f5_heat

# Enter the name of the heat engine service
heat_engine_service_name: : openstack-heat-engine  # openstack-heat-engine
